apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/web-app*.log
      pos_file /tmp/app.logs.pos
      tag kube.*
      format json
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

   

    <match kube.**>
      @type elasticsearch
      @log_level info
      host 116.103.226.146
      port 9200
      index_name ${tag}-log
      scheme https
      user elastic
      password iRsUoyhqW-CyyGdwk6V_
      ssl_verify false
      logstash_format true
      logstash_prefix loidq_0934829614
      include_tag_key true
      type_name _doc
      flush_interval 5s
    </match>
# host 116.103.226.146
# port 9200
# scheme https
# user elastic
# password iRsUoyhqW-CyyGdwk6V_
# index_name ${tag}-log
# logstash_format true
# logstash_prefix loidq_0934829614

# <match kube.**>
#       @type elasticsearch
#       @log_level info
#       host elasticsearch
#       port 9200
#       index_name ${tag}-log
#       logstash_format true
#       logstash_prefix loidq_0934829614
#       include_tag_key true
#       type_name _doc
#       flush_interval 5s
#     </match>