apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd
  template:
    metadata:
      labels:
        name: fluentd
    spec:
      securityContext:
        fsGroup: 2000 # Fluentd's group ID
        runAsUser: 1000 # Fluentd's user ID
      containers:
      - name: fluentd
        image: govtechsg/fluentd-elasticsearch
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "116.103.226.146"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: "elastic"
        - name: ELASTICSEARCH_PASSWORD
          value: "iRsUoyhqW-CyyGdwk6V_"
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
